apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kueue-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sleep-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: kueue_external_metric
      target:
        type: AverageValue
        averageValue: 2