---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-viewer
  namespace: kueue-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-viewer-role
rules:
  # Allows GET requests against /metrics (non-resource URL).
  # This is relevant if the service is protected by kube-rbac-proxy or similar.
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-viewer-rolebinding
subjects:
- kind: ServiceAccount
  name: metrics-viewer
  namespace: kueue-system
- kind: ServiceAccount
  name: backend-kueue
  namespace: default
roleRef:
  kind: ClusterRole
  name: metrics-viewer-role
  apiGroup: rbac.authorization.k8s.io

