# Url to access prometheus
prometheus:
  url: http://prom-kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090
  path: ""

rules:
  default: true

  custom: 
    - seriesQuery: '{__name__=~"^fastapi_inprogress_requests_total$"}'
      resources:
        template: <<.Resource>>
      name:
        matches: ""
        as: "fastapi_custom_metric"
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)

  external:
    - seriesQuery: '{__name__=~"^kueue_pending_workloads$"}'
      resources:
        template: <<.Resource>>
      name:
        matches: ""
        as: "kueue_external_metric"
      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)

